name: USP22-HGF
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - matplotlib=3.9.2
  - pillow=10.4.0
  - opencv
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=13.0
  - pip
  - pip:
      - reportlab==4.2.5
